[package]
name = "shared"
version = "0.1.0"
edition = "2021"
rust-version = "1.71.0"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typege=["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
serde = {workspace = true, features = ["derive"]}
lazy_static = "1.5.0"
uniffi = "0.28.0"
wasm-bindgen = "0.2.92"

[target.uniffi-bindgen.dependencies]
uniffi = {version = "0.28.0", features = ["cli"]}

[build-dependencies]
uniffi = {version = "0.28.0", features = ["build"]}

